### ISSUE TITLE
Resample時のエラー

### ISSUE THREAD

**Issue by shingo405nagano** [shingo405nagano/generating_topoglaphic_maps#11]
EPSG:4326のRasterをResampleするとエラーが出る。

UTMのEPSGを推定して計算し、最後に元に戻した方がいいか？

---
 - "最初にリサンプリングを行う" にチェックを入れる

AttributeError: 'NoneType' object has no attribute 'RasterXSize' 
Traceback (most recent call last):
  File "C:\Users/makis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_topography_original\topo_maps.py", line 188, in execute_algorithom
    composited_img, org_dst = worker.run(self.dlg, self.my_log)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/makis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_topography_original\topo_maps.py", line 249, in run
    if not msg.yes_no(org_dst):
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users/makis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_topography_original\apps\exeptions.py", line 65, in yes_no
    size = dst.RasterXSize * dst.RasterYSize
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'RasterXSize'

---
 - Slope のリサンプリングも

**Comment by shingo405nagano** [comment]
解決
